#!/bin/bash

# This script delete unused packages. Be vigilant and read carefully what he wants to remove

sudo dnf remove abrt \
	f37-backgrounds-gnome \
	nm-connection-editor \
	mozilla-filesystem \
	chrome-gnome-shell \
	quota \
	quota-devel \
	nmap-ncat \
	virtualbox-guest-additions \
	spice-vdagent \
	nfs-utils \
	teamd \
	tcpdump \
	sgpio \
	ImageMagick \
	adcli \
	libreoffice \
	lvm2 \
	qemu-guest-agent \
	hyperv \
	gnome-classic-session \
	baobab \
	libkkc-common \
	libzhuyin \
	libpinyin \
	evince \
	yelp \
	ModemManager \
	fedora-bookmarks \
	fedora-chromium-config \
	fedora-workstation-backgrounds \
	gnome-tour \
	gnome-themes-extra \
	gnome-shell-extension-background-logo \
	gnome-screenshot \
	gnome-remote-desktop \
	gnome-font-viewer \
	gnome-calculator \
	gnome-backgrounds \
	NetworkManager-pptp-gnome \
	NetworkManager-ssh-gnome \
	NetworkManager-openconnect-gnome \
	NetworkManager-openvpn-gnome \
	NetworkManager-vpnc-gnome \
	podman \
	libvirt \
	open-vm-tools \
	speech-tools \
	sos \
	totem \
	gnome-characters \
	firefox \
	eog \
	openssh-server \
	xorg-x11-drv-vmware \
	xorg-x11-drv-amdgpu \
	yajl \
	words \
	ibus-hangul \
	fcitx-hangul \
	fcitx5-hangul \
	openh264 \
	realmd \
	rsync \
	net-snmp-libs \
	net-tools \
	traceroute \
	mtr \
	geolite2-city \
	geolite2-country \
	gnome-boxes \
	gnome-disk-utility \
	cheese \
	gnome-contacts \
	rhythmbox \
	gnome-screenshot \
	gnome-maps \
	gnome-weather \
	gnome-logs \
	ibus-typing-booster \
	m17n-db \
	m17n-lib \
	gnome-clocks \
	gnome-color-manager \
	mlocate \
	cyrus-sasl-plain \
	cyrus-sasl-gssapi \
	sssd-client \
	sssd-common \
	sssd-kcm \
	gnome-user-docs \
	gnome-user-share \
	dos2unix \
	kpartx \
	rng-tools \
	ppp \
	thermald \
	gnome-shell-extension-horizontal-workspaces \
	gnome-shell-extension-launch-new-instance \
	gnome-shell-extension-window-list \
	sane-airscan \
	simple-scan
